### ISSUE TITLE
Listening on multiple interfaces

### ISSUE THREAD

**Issue by akarasulu** [thousandeyes/shoelaces#10]
Hi there, I'm enjoying the simplicity and ease of shoelaces. Thank you for it. However, I have a situation where I would like to specify a list of domains (ip addresses) in the configuration. Can probably do this with iptables but wondering if there is a way out of the box.

Thanks in advance.

**Comment by raul-te** [comment]
Hello @akarasulu, and thanks for your kind words and interest in this project.

Let me see if I understand correctly. You have a server with multiple interfaces and you would like Shoelaces to listen on them. If that's what you want, coincidentally we just released a new version of Shoelaces that segregates the base URL from the bind addr, so you could bind in all the interfaces with something like this in your config:
```
base-url=example.com:8081
bind-addr=:8081
```

Will this take care of your use case?

**Comment by akarasulu** [comment]
Perfect thanks @raul-te. Glad to see the project progressing. Such KISS solution that others in the space have yet to embrace. 

For prosperity, before your heads up, I used the following iptables workaround to quickly get by but will upgrade to the new release:

```shell
iptables -t nat -A PREROUTING --source 0/0 -p tcp --dport 8081 -j DNAT --to-destination 192.168.1.248:8081
```

Thanks again! Closing this issue.

**Comment by raul-te** [comment]
Good to know that it works for you, thanks!
