### ISSUE TITLE
Password auth

### ISSUE THREAD

**Issue by nwmcsween** [thousandeyes/shoelaces#11]
Allow per menu password auth, this fixes users from potentially nuking their installs by plugging into a vlan/jack they really shouldn't plug into..

**Comment by raul-te** [comment]
Hey @nwmcsween. Thanks for your interest in the project!

Could you add more information about this use case? If you want to password-protect certain pages, I think that setting that configuration on a webserver like apache or nginx is more appropriate.

**Comment by stappersg** [comment]
Twenty-three months ago:

> Could you add more information about this use case?

I think that the nearly two years of silence  should be rendered in _"No, I can NOT add more information the use case"_ and that this issue should be closed.

**Comment by raul-te** [comment]
Fair enough.
