### ISSUE TITLE
Automating iSCSI with Shoelaces

### ISSUE THREAD

**Issue by akarasulu** [thousandeyes/shoelaces#12]
Hi and thank you for Sheolaces.

I would like to get opinions on how to best integrate it with SAN Rest API's. I would like to automate the creation of iSCSI targets using these Rest APIs via Shoelaces. This involves calling the API endpoint to create the block device. How would you advise going about such an integration?

Thanks in advance.
Alex

**Comment by raul-te** [comment]
Hi Alex, and thank you for your interest in Shoelaces.

I think I don't have all the information to understand your use-case. Will these block devices be used for installing an OS on them via Shoelaces? Or you just want to create the targets—no matter what are they going to be used for— and automate that process via Shoelaces? 

If the later, then you _could_ use Shoelaces to get templates for calling the SAN API, but it's probably an overkill. You can probably do that with a small script.

If what you want to do is automate the installation of an OS using an iSCSI target as a root device, then that will depend on the OS's installer support for such devices. For example, Debian [does not seem to support it](https://wiki.debian.org/SAN/iSCSI).

**Comment by raul-te** [comment]
Closing. If you're able to provide the missing information, we can re-open.
