### ISSUE TITLE
Allow custom parameters to pytest.main

### ISSUE THREAD

**Issue by stappersg** [thousandeyes/shoelaces#21]
Good stuff, thanks for your contribution. Now that the [integration tests are working](https://github.com/thousandeyes/shoelaces/commit/5df23c99d98ba5515f882a050cc1986c7d75bca0), a new test case covering this new endpoint will be ideal.

_Originally posted by @raul-te in https://github.com/thousandeyes/shoelaces/issues/18#issuecomment-1371540144_

**Comment by stappersg** [comment]
Despite having
```diff
--- a/Makefile
+++ b/Makefile
@@ -19,8 +19,8 @@ shoelaces.8:
 docs: shoelaces.8
 
 test: fmt
-               $(GO) test -v $(pkgs) && \
-                       ./test/integ-test/integ_test.py
+               $(GO) test -vv $(pkgs) && \
+                       ./test/integ-test/integ_test.py -vv
 
 .PHONY: all clean docs
 
```
so `-vv` at two places, I keep getting
```text
=============================================== FAILURES ================================================
________________________________ test_request_response[/start-start.txt] ________________________________

shoelaces_instance = <Popen: returncode: None args: ['/usr/src/github/shoelaces/shoelaces', '-con...>
request_path = '/start', response_file = 'start.txt'

    @pytest.mark.parametrize(("request_path", "response_file"), REQUEST_RESPONSE_PAIRS)
    def test_request_response(shoelaces_instance, request_path, response_file):
        with open(os.path.join(FIXTURE_DIR, response_file)) as response_body:
>           assert requests.get(
                API_URL + request_path).text == response_body.read()
E           AssertionError: assert '#!ipxe\necho...ll receive.\n' == '#!ipxe\necho...ll receive.\n'
E               #!ipxe
E               echo Shoelaces starts polling
E               chain --autofree --replace \
E                   http://localhost:18888/poll/1/${netX/mac:hexhyp}
E               #
E               #
E               # Do...
E             
E             ...Full output truncated (5 lines hidden), use '-vv' to show

/usr/src/github/shoelaces/test/integ-test/integ_test.py:116: AssertionError
----------------------------------------- Captured stdout call ------------------------------------------
ts=2023-01-08T17:49:37.517846401Z caller=server.go:2109 level=info component=http type=request src=127.0.0.1:57620 method=GET url=/start
======================================== short test summary info ========================================
FAILED test/integ-test/integ_test.py::test_request_response[/start-start.txt] - AssertionError: assert...
===================================== 1 failed, 34 passed in 0.35s ======================================
```

Repeating the
```text
E             ...Full output truncated (5 lines hidden), use '-vv' to show
```
Where to add the `-vv`?

**Comment by stappersg** [comment]
The problem of _"Where to add the `-vv`?"_ can been seen with either #22 or #23.

**Comment by raul-te** [comment]
The parameters to `pytest.main` are [hardcoded](https://github.com/thousandeyes/shoelaces/blob/5df23c99d98ba5515f882a050cc1986c7d75bca0/test/integ-test/integ_test.py#L216):

```python
if __name__ == "__main__":
    pytest.main(args=['-v'], plugins=None)
```

Ideally, would like to support custom parameters to have the flexibility of choosing either `-v` or `-vv`.

**Comment by stappersg** [comment]
> > Where to add the -vv?

> The parameters to `pytest.main` are [hardcoded](https://github.com/thousandeyes/shoelaces/blob/5df23c99d98ba5515f882a050cc1986c7d75bca0/test/integ-test/integ_test.py#L216):
> 
> ```python
> if __name__ == "__main__":
>     pytest.main(args=['-v'], plugins=None)
> ```
> 
> Ideally, would like to support custom parameters to have the flexibility of choosing either `-v` or `-vv`.

There is now #26.

**Comment by raul-te** [comment]
I think we will benefit if we add support for passing custom parameters to `integ_test.py`. Let me know if you're interested in implementing this feature.

We should leave the issue open until the feature reaches `master`.

**Comment by stappersg** [comment]
On Tue, Jan 17, 2023 at 10:53:01AM -0800, Raul Benencia wrote:
> Let me know if you're interested in implementing this feature.

Frankly: No

**Comment by stappersg** [comment]
I did not create this issue with subject _"Allow custom parameters to pytest.main"_
and I don't like the _opened_ by me in the overview.

![image](https://user-images.githubusercontent.com/35434094/230597811-1127034c-6a6c-4ab9-a803-47a404288fb2.png)

So now another close attempt.
