### ISSUE TITLE
Please support subdirectories for files

### ISSUE THREAD

**Issue by formorer** [thousandeyes/shoelaces#4]
It is not possible - at least I have no idea how - to create templates that a served from a subdirectory. Background:

- we are using cloud-init with the nocloud provider with the seed parameter, that let clould-init look in basedir/user-data basedir/meta-data for files. We don't want to set the seed basedirectory to / and would prefer to serve the templates under a subdirectory within our config. The naive approach of _{{define "puppetschulung/meta-data" -}}_ didn't work.

**Comment by q2dg** [comment]
Well, this project seems pretty abandoned...

**Comment by raul-te** [comment]
Hey @formorer, I've just released Shoelaces v1.1.0 which implements configs subdirectories. Thanks for requesting the feature, and sorry it took me a while to get to it.

Cheers!
